[package]
name = "sieve"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus = "0.8.1"
alloy-primitives = "0.8.15"
alloy-rpc-types = "0.8.1"
alloy-rpc-types-eth = "0.8.1"
alloy-rpc-types-txpool = "0.8.1"
dashmap = "6.1.0"
serde_json = "1.0.133"


[lints.clippy]
